{% set name = "pymeos-cffi" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 8b490d5ed8434ed9df404404a12d58034bc02c14a1599e9db280de0367635d43

build:
  skip: true  # [s390x or win or py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=61.0
    - cffi
    - pip
    - wheel
    - meos >=1.2,<1.3
  run:
    - python
    - cffi
    - meos >=1.2,<1.3
    - python-dateutil
    - shapely

test:
  imports:
    - pymeos_cffi
  commands:
    - pip check
    - python -c "import pymeos_cffi; pymeos_cffi.meos_initialize('UTC'); pymeos_cffi.meos_finalize();"
  requires:
    - pip

about:
  summary: Python wrapper for the MEOS C Library.
  description: |
    PyMEOS CFFI is a Python wrapper for the MEOS C Library. It wraps all the exposed functions and takes care of many
    of the necessary conversions between Python and C data types, as well as managing the errors occurring in the C
    library.
  license: PostgreSQL
  license_family: OTHER
  license_file: LICENSE.txt
  home: https://pymeos.readthedocs.io
  doc_url: https://pymeos.readthedocs.io
  dev_url: https://github.com/MobilityDB/PyMEOS

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
  skip-lints:
    - host_section_needs_exact_pinnings